const siteUrl = "https://shelter4u.in";

/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl,
  generateRobotsTxt: true,
  robotsTxtOptions: {
    policies: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/api/"],
      },
    ],
    additionalSitemaps: [`${siteUrl}/sitemap.xml`],
  },
  exclude: ["/api/*"],
  // We will generate additional paths using a pre-script or by calling an API
  // but for now let's use the additionalPaths property
  additionalPaths: async (config) => {
    // In a real postbuild, we would fetch from DB here
    // However, since we want to keep it simple and avoid path alias issues
    // we can use a JSON file generated by a pre-script
    const fs = require("fs");
    const path = require("path");
    const pathsFile = path.join(__dirname, "dynamic-paths.json");

    if (fs.existsSync(pathsFile)) {
      const dynamicPaths = JSON.parse(fs.readFileSync(pathsFile, "utf8"));
      return dynamicPaths.map((p) => ({
        loc: p,
        changefreq: "daily",
        priority: 0.7,
        lastmod: new Date().toISOString(),
      }));
    }
    return [];
  },
};
